using System.Globalization;
using CodexProfileOverlay.Core.Models;

namespace CodexProfileOverlay.Core.Services;

public static class LocalizationCatalog
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["OpenCodex"] = "Open Codex",
        ["ShowSwitcher"] = "Show switcher",
        ["HideSwitcher"] = "Hide switcher",
        ["Profiles"] = "Profiles",
        ["Settings"] = "Settings",
        ["StartWithWindows"] = "Start with Windows",
        ["Exit"] = "Exit",
        ["Active"] = "Active",
        ["AddProfile"] = "Add profile",
        ["ManageProfiles"] = "Manage profiles",
        ["Rename"] = "Rename",
        ["OpenFolder"] = "Open folder",
        ["Remove"] = "Remove",
        ["SwitchingToProfile"] = "Switching to {0}...",
        ["SwitchedToAccount"] = "Switched to account: {0}",
        ["PreviousAuthorizationRestored"] = "Previous authorization was restored",
        ["General"] = "General",
        ["Appearance"] = "Appearance",
        ["Hotkeys"] = "Hotkeys",
        ["Language"] = "Language",
        ["ThemeLight"] = "Light theme",
        ["ThemeDark"] = "Dark theme",
        ["SwitchToLightTheme"] = "Switch to light theme",
        ["SwitchToDarkTheme"] = "Switch to dark theme",
        ["Advanced"] = "Advanced",
        ["Close"] = "Close",
        ["Refresh"] = "Refresh",
        ["Done"] = "Done",
        ["NoReadyProfiles"] = "No ready profiles",
        ["ToggleSwitcher"] = "Toggle switcher",
        ["RestoreDefaults"] = "Restore defaults",
        ["ResetHotkeys"] = "Reset hotkeys",
        ["PressShortcut"] = "Press a shortcut...",
        ["None"] = "None",
        ["Applied"] = "Applied",
        ["DisplayMode"] = "Display mode",
        ["PositionPreset"] = "Position preset",
        ["OffsetX"] = "X offset",
        ["OffsetY"] = "Y offset",
        ["UiScale"] = "UI scale",
        ["Animations"] = "Animations",
        ["ShowAutomatically"] = "Show automatically when Codex opens",
        ["LaunchOnStart"] = "Launch Codex when overlay starts",
        ["LaunchAfterSwitch"] = "Launch Codex after switching",
        ["GracefulTimeout"] = "Graceful close timeout",
        ["ForceCloseFallback"] = "Force-close fallback",
        ["ConfirmForceClose"] = "Confirm account switch",
        ["ConfirmSwitchTitle"] = "Switch account?",
        ["ConfirmSwitchPrompt"] = "Codex will close and switch to profile \"{0}\". The account will only be changed after you confirm.",
        ["ConfirmSwitchPrimary"] = "Switch account",
        ["CodexCouldNotLaunch"] = "Codex could not be opened automatically.",
        ["SystemDefault"] = "System default",
        ["English"] = "English",
        ["Russian"] = "Русский",
        ["DirectoryName"] = "Directory name",
        ["OpenProfilesFolder"] = "Open profiles folder",
        ["OpenRemovedProfilesFolder"] = "Open removed profiles folder",
        ["OpenApplicationData"] = "Open app data",
        ["OpenBackups"] = "Open backups",
        ["OpenLogs"] = "Open logs",
        ["ResetPosition"] = "Reset position",
        ["ResetSettings"] = "Reset settings",
        ["ExitApplication"] = "Exit application",
        ["CouldNotRefreshProfiles"] = "Could not refresh profiles. Check the profiles folder.",
        ["HotkeysCouldNotRegister"] = "One or more hotkeys could not be registered.",
        ["ForceClosePrompt"] = "Codex will be asked to close gracefully. If it is still running after the timeout, allow force closing Codex to complete the switch?",
        ["CouldNotSwitch"] = "Could not switch account.",
        ["AddProfileTitle"] = "Add profile",
        ["ProfileDirectoryName"] = "Profile directory name",
        ["StartingLogin"] = "Starting Codex login for {0}...",
        ["AuthNotCreated"] = "Login finished, but auth.json was not created.",
        ["ProfileAdded"] = "Profile added successfully",
        ["SwitchNewProfile"] = "Switch to the newly added profile now?",
        ["CouldNotAddProfile"] = "Could not add profile.",
        ["RenameDisplayName"] = "Rename display name",
        ["DisplayName"] = "Display name",
        ["ProfileRenamed"] = "Profile renamed",
        ["ActiveProfileCannotRename"] = "The active profile folder cannot be renamed.",
        ["ActiveProfileCannotRemove"] = "The active profile cannot be removed.",
        ["RemoveProfilePrompt"] = "This moves the local saved login to the removed-profiles folder. It does not delete your ChatGPT account.",
        ["ProfileRemoved"] = "Profile removed from switcher",
        ["StartupCouldNotUpdate"] = "Start with Windows could not be updated.",
        ["Add"] = "Add",
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["DisplayModeHelp"] = "Auto chooses compact mode for narrow Codex windows.",
        ["PositionPresetHelp"] = "After menu places the switcher just to the right of the native menu row.",
        ["OffsetXHelp"] = "Drag horizontally or type a value.",
        ["OffsetYHelp"] = "Drag vertically or type a value.",
        ["UiScaleHelp"] = "Scale the overlay without changing Codex.",
        ["AnimationsHelp"] = "Enables short hover and notification transitions.",
        ["StartWithWindowsHelp"] = "Registers the published executable for Windows sign-in.",
        ["ShowAutomaticallyHelp"] = "Controls automatic display when a Codex window is available.",
        ["LaunchOnStartHelp"] = "Starts Codex when this tray app starts.",
        ["LaunchAfterSwitchHelp"] = "Reopens Codex after a completed account switch.",
        ["LanguageHelp"] = "System default follows Windows display language.",
        ["GracefulTimeoutHelp"] = "Seconds to wait before optional force-close fallback.",
        ["ForceCloseFallbackHelp"] = "Allows switching to complete if Codex does not close gracefully.",
        ["ConfirmForceCloseHelp"] = "Asks before Codex is closed and the active account is changed.",
        ["HotkeyHelp"] = "Click the field, then press the shortcut. Escape cancels; Backspace clears.",
        ["UseModifier"] = "Use at least one modifier.",
        ["InvalidNumber"] = "Invalid number.",
        ["CouldNotSaveSettings"] = "Could not save settings.",
        ["ExportSettings"] = "Export settings",
        ["ImportSettings"] = "Import settings",
        ["ProfileHotkey"] = "Profile {0}: {1}",
        ["Switching"] = "Switching...",
        ["AfterMenu"] = "After menu",
        ["TopCenter"] = "Top center",
        ["TopRight"] = "Top right",
        ["TopLeft"] = "Top left",
        ["Custom"] = "Custom",
        ["Auto"] = "Auto",
        ["Compact"] = "Compact",
        ["Expanded"] = "Expanded",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["OpenCodex"] = "Открыть Codex",
        ["ShowSwitcher"] = "Показать переключатель",
        ["HideSwitcher"] = "Скрыть переключатель",
        ["Profiles"] = "Профили",
        ["Settings"] = "Настройки",
        ["StartWithWindows"] = "Запускать вместе с Windows",
        ["Exit"] = "Выйти",
        ["Active"] = "Активен",
        ["AddProfile"] = "Добавить профиль",
        ["ManageProfiles"] = "Управление профилями",
        ["Rename"] = "Переименовать",
        ["OpenFolder"] = "Открыть папку",
        ["Remove"] = "Удалить",
        ["SwitchingToProfile"] = "Переключение на {0}...",
        ["SwitchedToAccount"] = "Аккаунт переключён: {0}",
        ["PreviousAuthorizationRestored"] = "Предыдущая авторизация восстановлена",
        ["General"] = "Общие",
        ["Appearance"] = "Внешний вид",
        ["Hotkeys"] = "Горячие клавиши",
        ["Language"] = "Язык",
        ["ThemeLight"] = "Светлая тема",
        ["ThemeDark"] = "Темная тема",
        ["SwitchToLightTheme"] = "Включить светлую тему",
        ["SwitchToDarkTheme"] = "Включить темную тему",
        ["Advanced"] = "Дополнительно",
        ["Close"] = "Закрыть",
        ["Refresh"] = "Обновить",
        ["Done"] = "Готово",
        ["NoReadyProfiles"] = "Нет готовых профилей",
        ["ToggleSwitcher"] = "Переключить панель",
        ["RestoreDefaults"] = "Восстановить по умолчанию",
        ["ResetHotkeys"] = "Сбросить хоткеи",
        ["PressShortcut"] = "Нажмите сочетание...",
        ["None"] = "Нет",
        ["Applied"] = "Применено",
        ["DisplayMode"] = "Режим отображения",
        ["PositionPreset"] = "Положение",
        ["OffsetX"] = "Смещение X",
        ["OffsetY"] = "Смещение Y",
        ["UiScale"] = "Масштаб UI",
        ["Animations"] = "Анимации",
        ["ShowAutomatically"] = "Показывать автоматически при открытии Codex",
        ["LaunchOnStart"] = "Запускать Codex при старте панели",
        ["LaunchAfterSwitch"] = "Запускать Codex после переключения",
        ["GracefulTimeout"] = "Таймаут мягкого закрытия",
        ["ForceCloseFallback"] = "Принудительное закрытие при сбое",
        ["ConfirmForceClose"] = "Подтверждать смену аккаунта",
        ["ConfirmSwitchTitle"] = "Переключить аккаунт?",
        ["ConfirmSwitchPrompt"] = "Codex будет закрыт и переключится на профиль \"{0}\". Аккаунт сменится только после подтверждения.",
        ["ConfirmSwitchPrimary"] = "Переключить",
        ["CodexCouldNotLaunch"] = "Не удалось автоматически открыть Codex.",
        ["SystemDefault"] = "Как в системе",
        ["English"] = "English",
        ["Russian"] = "Русский",
        ["DirectoryName"] = "Имя папки",
        ["OpenProfilesFolder"] = "Открыть папку профилей",
        ["OpenRemovedProfilesFolder"] = "Открыть удалённые профили",
        ["OpenApplicationData"] = "Открыть данные приложения",
        ["OpenBackups"] = "Открыть резервные копии",
        ["OpenLogs"] = "Открыть логи",
        ["ResetPosition"] = "Сбросить положение",
        ["ResetSettings"] = "Сбросить настройки",
        ["ExitApplication"] = "Выйти из приложения",
        ["CouldNotRefreshProfiles"] = "Не удалось обновить профили. Проверьте папку профилей.",
        ["HotkeysCouldNotRegister"] = "Не удалось зарегистрировать одну или несколько горячих клавиш.",
        ["ForceClosePrompt"] = "Codex будет закрыт штатно. Если он продолжит работать после таймаута, разрешить принудительное закрытие для завершения переключения?",
        ["CouldNotSwitch"] = "Не удалось переключить аккаунт.",
        ["AddProfileTitle"] = "Добавить профиль",
        ["ProfileDirectoryName"] = "Имя папки профиля",
        ["StartingLogin"] = "Запуск входа Codex для {0}...",
        ["AuthNotCreated"] = "Вход завершён, но auth.json не был создан.",
        ["ProfileAdded"] = "Профиль успешно добавлен",
        ["SwitchNewProfile"] = "Переключиться на новый профиль сейчас?",
        ["CouldNotAddProfile"] = "Не удалось добавить профиль.",
        ["RenameDisplayName"] = "Переименовать отображаемое имя",
        ["DisplayName"] = "Отображаемое имя",
        ["ProfileRenamed"] = "Профиль переименован",
        ["ActiveProfileCannotRename"] = "Папку активного профиля нельзя переименовать.",
        ["ActiveProfileCannotRemove"] = "Активный профиль нельзя удалить.",
        ["RemoveProfilePrompt"] = "Локальный сохранённый вход будет перемещён в папку removed-profiles. Это не удаляет ваш аккаунт ChatGPT.",
        ["ProfileRemoved"] = "Профиль удалён из переключателя",
        ["StartupCouldNotUpdate"] = "Не удалось обновить запуск вместе с Windows.",
        ["Add"] = "Добавить",
        ["Save"] = "Сохранить",
        ["Cancel"] = "Отмена",
        ["DisplayModeHelp"] = "Авто включает компактный режим для узких окон Codex.",
        ["PositionPresetHelp"] = "После меню размещает переключатель справа от встроенной строки меню.",
        ["OffsetXHelp"] = "Перетащите по горизонтали или введите значение.",
        ["OffsetYHelp"] = "Перетащите по вертикали или введите значение.",
        ["UiScaleHelp"] = "Масштабирует оверлей, не меняя Codex.",
        ["AnimationsHelp"] = "Включает короткие анимации наведения и уведомлений.",
        ["StartWithWindowsHelp"] = "Регистрирует опубликованный exe для входа в Windows.",
        ["ShowAutomaticallyHelp"] = "Управляет автоматическим показом, когда доступно окно Codex.",
        ["LaunchOnStartHelp"] = "Запускает Codex при старте этого приложения.",
        ["LaunchAfterSwitchHelp"] = "Открывает Codex после успешного переключения аккаунта.",
        ["LanguageHelp"] = "Системный режим следует языку интерфейса Windows.",
        ["GracefulTimeoutHelp"] = "Сколько секунд ждать перед запасным принудительным закрытием.",
        ["ForceCloseFallbackHelp"] = "Позволяет завершить переключение, если Codex не закрылся штатно.",
        ["ConfirmForceCloseHelp"] = "Спрашивает подтверждение перед закрытием Codex и сменой активного аккаунта.",
        ["HotkeyHelp"] = "Нажмите поле, затем сочетание клавиш. Escape отменяет, Backspace очищает.",
        ["UseModifier"] = "Используйте хотя бы один модификатор.",
        ["InvalidNumber"] = "Некорректное число.",
        ["CouldNotSaveSettings"] = "Не удалось сохранить настройки.",
        ["ExportSettings"] = "Экспорт настроек",
        ["ImportSettings"] = "Импорт настроек",
        ["ProfileHotkey"] = "Профиль {0}: {1}",
        ["Switching"] = "Переключение...",
        ["AfterMenu"] = "После меню",
        ["TopCenter"] = "Сверху по центру",
        ["TopRight"] = "Сверху справа",
        ["TopLeft"] = "Сверху слева",
        ["Custom"] = "Своя позиция",
        ["Auto"] = "Авто",
        ["Compact"] = "Компактный",
        ["Expanded"] = "Развернутый",
    };

    public static LanguagePreference Resolve(LanguagePreference preference, CultureInfo? culture = null)
    {
        if (preference != LanguagePreference.SystemDefault)
        {
            return preference;
        }

        culture ??= CultureInfo.CurrentUICulture;
        return culture.TwoLetterISOLanguageName.Equals("ru", StringComparison.OrdinalIgnoreCase)
            ? LanguagePreference.Russian
            : LanguagePreference.English;
    }

    public static string Text(LanguagePreference preference, string key, params object[] args)
    {
        IReadOnlyDictionary<string, string> dictionary = Resolve(preference) == LanguagePreference.Russian ? Russian : English;
        string value = dictionary.TryGetValue(key, out string? text)
            ? text
            : English.GetValueOrDefault(key, key);
        return args.Length == 0 ? value : string.Format(CultureInfo.CurrentCulture, value, args);
    }

    public static IReadOnlyCollection<string> MissingRussianKeys()
    {
        return English.Keys.Where(key => !Russian.ContainsKey(key)).Order(StringComparer.Ordinal).ToArray();
    }
}
